# Generated by Django 3.2 on 2021-05-02 20:50

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('identifier', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(blank=True, max_length=160)),
                ('work_title', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('identifier', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('publication_time', models.DateTimeField()),
                ('view_count', models.BigIntegerField()),
                ('text', models.TextField()),
                ('header', models.CharField(max_length=360)),
                ('author', models.ForeignKey(on_delete=models.SET(news.models.get_deleted_author), to='news.author')),
            ],
            options={
                'ordering': ['-publication_time'],
            },
        ),
    ]
