# Generated by Django 3.2 on 2021-05-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210503_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='publication_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
